"""
Catalogo de endpoints /records y tablas auxiliares para import_data.py.
"""

# Listados paginados JSON (datos de negocio)
DATA_RECORDS_ENDPOINTS: list[tuple[str, str]] = [
    ("categories", "/categories/records"),
    ("items", "/items/records"),
    ("customers", "/persons/customers/records"),
    ("suppliers", "/persons/suppliers/records"),
    ("documents", "/documents/records"),
    ("documents_not_sent", "/documents/not-sent/records"),
    ("sale_notes", "/sale-notes/records"),
    ("quotations", "/quotations/records"),
    ("order_notes", "/order-notes/records"),
    ("purchases", "/purchases/records"),
    ("purchase_orders", "/purchase-orders/records"),
    ("purchase_quotations", "/purchase-quotations/records"),
    ("expenses", "/expenses/records"),
    ("inventory", "/inventory/records"),
    ("inventory_references", "/inventory-references/records"),
    ("transfers", "/transfers/records"),
    ("devolutions", "/devolutions/records"),
    ("dispatches", "/dispatches/records"),
    ("cash", "/cash/records"),
    ("users", "/users/records"),
    ("establishments", "/establishments/records"),
    ("brands", "/brands/records"),
    ("series", "/series/records"),
    ("zones", "/zones/records"),
    ("person_types", "/person-types/records"),
    ("voided", "/voided/records"),
    ("summaries", "/summaries/records"),
    ("finances_movements", "/finances/movements/records"),
    ("finances_unpaid", "/finances/unpaid/records"),
    ("finances_to_pay", "/finances/to-pay/records"),
    ("finances_income", "/finances/income/records"),
    ("exchange_currency", "/exchange_currency/records"),
    ("vehicles", "/vehicles/records"),
    ("drivers", "/drivers/records"),
    ("dispatchers", "/dispatchers/records"),
    ("transports", "/transports/records"),
    ("payroll", "/payroll/records"),
    ("retentions", "/retentions/records"),
    ("perceptions", "/perceptions/records"),
    ("cupones", "/cupones/records"),
    ("item_sets", "/item-sets/records"),
    ("item_lots", "/item-lots/records"),
    ("item_lots_group", "/item-lots-group/records"),
    ("price_adjustments", "/price-adjustments/records"),
    ("discount_types", "/discount-types/records"),
    ("technical_services", "/technical-services/records"),
    ("contingencies", "/contingencies/records"),
    ("sire_sale", "/sire/sale/records"),
    ("sire_purchase", "/sire/purchase/records"),
    ("sire_appendix", "/sire/appendix/records"),
]

# Respuestas JSON no paginadas (catálogos completos)
DATA_TABLE_ENDPOINTS: list[tuple[str, str]] = [
    ("pos_tables", "/pos/tables"),
    ("documents_tables", "/documents/tables"),
    ("items_columns", "/items/columns"),
]
